// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package components

// File - Represents a file associated with a library item.
type File struct {
	// Unique identifier for the file.
	ID *int64 `json:"id,omitempty"`
	// The size of the file in bytes.
	Size *string `json:"size,omitempty"`
	// The TechPort URL at which the file is accessible for download.
	URL *string `json:"url,omitempty"`
}

func (o *File) GetID() *int64 {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *File) GetSize() *string {
	if o == nil {
		return nil
	}
	return o.Size
}

func (o *File) GetURL() *string {
	if o == nil {
		return nil
	}
	return o.URL
}
