// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package components

// LibraryItem - Represents a specific library item that is part of this project.
type LibraryItem struct {
	// Date the library item was completed.
	CompletionDate *string `json:"completionDate,omitempty"`
	// Description of the library item.
	Description *string `json:"description,omitempty"`
	// External URL for the library item.
	ExternalURL *string `json:"externalUrl,omitempty"`
	// List of files associated with the library item.
	Files []File `json:"files,omitempty"`
	// Unique identifier for the library item.
	ID *int64 `json:"id,omitempty"`
	// Publisher of the library item.
	PublishedBy *string `json:"publishedBy,omitempty"`
	// Date the library item was published.
	PublishedDate *string `json:"publishedDate,omitempty"`
	// Title of the library item
	Title *string `json:"title,omitempty"`
	// Identifies the type of library item, e.g. Image
	Type *string `json:"type,omitempty"`
}

func (o *LibraryItem) GetCompletionDate() *string {
	if o == nil {
		return nil
	}
	return o.CompletionDate
}

func (o *LibraryItem) GetDescription() *string {
	if o == nil {
		return nil
	}
	return o.Description
}

func (o *LibraryItem) GetExternalURL() *string {
	if o == nil {
		return nil
	}
	return o.ExternalURL
}

func (o *LibraryItem) GetFiles() []File {
	if o == nil {
		return nil
	}
	return o.Files
}

func (o *LibraryItem) GetID() *int64 {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *LibraryItem) GetPublishedBy() *string {
	if o == nil {
		return nil
	}
	return o.PublishedBy
}

func (o *LibraryItem) GetPublishedDate() *string {
	if o == nil {
		return nil
	}
	return o.PublishedDate
}

func (o *LibraryItem) GetTitle() *string {
	if o == nil {
		return nil
	}
	return o.Title
}

func (o *LibraryItem) GetType() *string {
	if o == nil {
		return nil
	}
	return o.Type
}
