// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package components

// Organization - A NASA center/facility associated with an project.
type Organization struct {
	// The acronym of the organization.
	Acronym *string `json:"acronym,omitempty"`
	// The city in which the organization is located.
	City *string `json:"city,omitempty"`
	// The name of the organization.
	Name *string `json:"name,omitempty"`
	// The state in which the organization is located.
	State *string `json:"state,omitempty"`
}

func (o *Organization) GetAcronym() *string {
	if o == nil {
		return nil
	}
	return o.Acronym
}

func (o *Organization) GetCity() *string {
	if o == nil {
		return nil
	}
	return o.City
}

func (o *Organization) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *Organization) GetState() *string {
	if o == nil {
		return nil
	}
	return o.State
}
