// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package components

// TechnologyArea - The Technology Area for a given technology that corresponds to the NASA Technology Roadmap.
type TechnologyArea struct {
	// The code identifier for the Technology Area.
	Code *string `json:"code,omitempty"`
	// Unique identifier for the Technology Area.
	ID *int64 `json:"id,omitempty"`
	// The name of the Technology Area.
	Name *string `json:"name,omitempty"`
}

func (o *TechnologyArea) GetCode() *string {
	if o == nil {
		return nil
	}
	return o.Code
}

func (o *TechnologyArea) GetID() *int64 {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *TechnologyArea) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}
